version: '2'
services:
  auth:
    build: ./Auth
    ports:
     - "8000:8000"
    depends_on:
     - database-hexology
    environment:
     - DATABASE_HOST=database-hexology
  hexo:
    build: ./app
    ports:
     - "80:3000"
    depends_on:
     - database-hexology
     - auth
    environment:
     - DATABASE_HOST=database-hexology
     - AUTH_HOST=auth
  database-hexology:
    image: gloverac/hexdb:latest