version: '2'
services:
  hexo:
    image: gloverac/hexweb:latest
    ports:
     - "80:3000"
    depends_on:
     - database-hexology
    environment:
     - DATABASE_HOST=database-hexology
  database-hexology:
    image: gloverac/hexodb:latest